export const cardsData = [
  {
    id: "p01",
    product: "Slider colcci",
    about: "Slider colcci em varias cores, super confortavel",
    price:  139.90,
    src: "Slider colcci.jpg",
    alt:"Slider colcci em varias cores, super confortavel",
    item:"calcado",
  
  },
  {
    id: "p02",
    product: "Sandália colcci",
    about: "Sandalia colcci em varias cores, super confortavel",
    price:  99.90,
    src: "Sandália colcci.jpg",
    alt:"Sandalia colcci em varias cores, super confortavel",
    item:"calcado",
  },
  {
    id: "p03",
    product: "Vestido Colcci Fitness",
    about: "Vestidos colcci em varias cores e tecido super leve",
    price:  169.90,
    src: "VESTIDO COLCCI FITNESS.jpg",
    alt:"Vestidos colcci em varias cores e tecido super leve",
    item:"roupa",
  },
  {
    id: "p04",
    product: "Bolsa colcci",
    about: "Bolsa colcci em varias cores, para varias ocasioes",
    price:  289.90,
    src: "bolsa colcci.png",
    alt:"Bolsa colcci em varias cores, para varias ocasioes",
    item:"acessorio",
  }, 
  {
    id: "p05",
    product: "Bolsa CCM",
    about: "Bolsa CCM",
    price:  149.0 ,
    src: "Bolsa CCM.jpg",
    alt:"Imagem de bolsa ccm ",
    item:"acessorio",
  },
  {
    id: "p06",
    product: "Carteira Colcci",
    about: "carteira super clean ",
    price:  69.90,
    src: "Carteira Colcci.jpg",
    alt:"Imagem de carteira colcci",
    item:"acessorio",
  },
  {
    id: "p07",
    product: "Garrafa dobravel LIVE",
    about: "Garrafa termica de otima qualidade",
    price: 109.90,
    src: "Garrafa dobravel LIVE.jpg",
    alt:"Imagem de garraga dobravel live ",
    item:"acessorio",
  },
   {
    id: "p08",
    product: "Rasteira colcci",
    about: "Rasteira basica super confortavel ",
    price:  149.0 ,
    src: "Rasteira colcci.jpg",
    alt:"Imagem de uma rasteira colcci ",
    item:"calcado",
  },
  {
    id: "p09",
    product: "regata colcci fitness",
    about: "Regata colcci super confortavel",
    price:  89.0 ,
    src: "regata colcci fitness.jpg",
    alt:"Imagem de uma regata colcci",
    item:"roupa",
  },
  {
    id: "p10",
    product: "Tênis LABELLAMAFIA",
    about: "Tenis branco labellamafia casual para todas ocasioes",
    price:  379.90,
    src: "TÊNIS LABELLAMAFIA.jpg",
    alt:"Imagem de um tenis labellamafia",
    item:"calcado"
  },
 
];

